# =========== DATASOURCE DEV ===========
spring.datasource.url=jdbc:postgresql://localhost:5432/weather
spring.datasource.username=bard
spring.datasource.password=403040
spring.datasource.driver-class-name=org.postgresql.Driver
# =========== JPA/HIBERNATE DEV ===========
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
hibernate.show_sql=true
hibernate.format_sql=true
# =========== LOGGING DEV ===========
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.bard.wether=DEBUG
# =========== WEATHER API DEV ===========
weather.api.key=fc1e39b85ff6b83957c733adb0e65cf8
# =========== ???????????? DEV ===========
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=false
server.servlet.session.cookie.same-site=lax
# =========== LIQUIBASE DEV ===========
# spring.liquibase.drop-first=true