#server.servlet.session.timeout=10m
#server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.secure=true
#server.servlet.session.cookie.same-site=strict
#server.servlet.session.cookie.name=JSESSIONID
#
## Datasource
#spring.datasource.url=jdbc:postgresql://localhost:5432/weather
#spring.datasource.username=bard
#spring.datasource.password=403040
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA/Hibernate -
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#
## Hibernate
#hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#hibernate.jdbc.batch_size=20
#hibernate.show_sql=true
#hibernate.format_sql=true
#
#
## For development
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#
##Liquibase
#spring.liquibase.default-schema=public
#spring.liquibase.enabled=true
#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#
##???? ??? ??????????
##spring.liquibase.drop-first=true
#
#
#weather.api.key=fc1e39b85ff6b83957c733adb0e65cf8
#weather.api.url=https://api.openweathermap.org/data/2.5
#
#
##
#session.timeout.hours=2
#
#
#spring.datasource.hikari.maximum-pool-size=20
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.idle-timeout=600000
#spring.datasource.hikari.max-lifetime=1800000
#
##Cookie
#cookie.max.age=7200
#cookie.default.name=SESSION_ID
#
#coordiantes.scale=6
#
#
#
#spring.profiles.active=dev
#
spring.profiles.active=dev
# =========== SERVER ===========
server.servlet.session.timeout=10m
server.servlet.session.cookie.name=JSESSIONID
# =========== JPA/HIBERNATE  ===========
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.jdbc.batch_size=20
# =========== LIQUIBASE  ===========
spring.liquibase.default-schema=public
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
# =========== WEATHER API  ===========
weather.api.url=https://api.openweathermap.org/data/2.5
# =========== SESSION  ===========
session.timeout.hours=2
# =========== HIKARI POOL ===========
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
# =========== COOKIE  ===========
cookie.max.age=7200
cookie.default.name=SESSION_ID
# =========== APP  ===========
coordiantes.scale=6